using Erp.Api.Common.Entities;
using Erp.Api.Common.Results;

namespace Erp.Api.Domain.Assemblies;

/// <summary>
/// One node of the machine breakdown â€” a section, an assembly or a sub-assembly.
/// <para>
/// Three master screens, one table, one class. That much the legacy system had
/// right: its <c>Assembly</c> table held all three, discriminated by a
/// <see cref="Level"/> column. What it did not have was any of the structure that
/// makes the arrangement safe â€”
/// </para>
/// <list type="bullet">
/// <item><description>
/// the parent link was the parent's <em>code</em> stored as a string with no
/// foreign key, so a section could be deleted out from under its assemblies;
/// </description></item>
/// <item><description>
/// a section pointed at the literal <c>"000"</c> rather than at nothing, so
/// "top of the tree" was a magic value every query had to know about;
/// </description></item>
/// <item><description>
/// the level rules lived in three separate save methods that disagreed with
/// each other â€” see <see cref="AssemblyLevels"/>;
/// </description></item>
/// <item><description>
/// and codes were generated by reading the whole table into memory, parsing the
/// numeric tail of each code and adding one, which two concurrent saves resolve
/// to the same number.
/// </description></item>
/// </list>
/// <para>
/// Here the parent is a real self-referencing foreign key, the level rules are one
/// lookup, and the code is supplied by the caller until the shared number-series
/// allocator exists â€” see <see cref="Create"/>.
/// </para>
/// <para>
/// The type is <c>internal</c>: outside Masters, a node is only ever a DTO or an id.
/// </para>
/// </summary>
public sealed class AssemblyNode
    : AggregateRoot<AssemblyNodeId>, IAuditable, ISoftDeletable, IBusinessUnitScoped, IHasRowVersion
{
    /// <summary>For EF materialisation only.</summary>
    private AssemblyNode()
    {
    }

    private AssemblyNode(AssemblyNodeId id, AssemblyLevel level, AssemblyNodeId? parentId, string code, string name)
        : base(id)
    {
        Level = level;
        ParentId = parentId;
        Code = code;
        Name = name;
    }

    /// <summary>
    /// Where this node sits in the breakdown. Set once, at creation.
    /// <para>
    /// Not editable, and deliberately: promoting a sub-assembly to a section is not
    /// an edit to a record, it is a different record with different children and a
    /// different parent. Allowing it as a field change would leave the tree in a
    /// shape no rule here can describe.
    /// </para>
    /// </summary>
    public AssemblyLevel Level { get; private set; }

    /// <summary>
    /// The node directly above. Null only for a <see cref="AssemblyLevel.Section"/>.
    /// A real foreign key onto this same table â€” see <c>AssemblyNodeConfiguration</c>.
    /// </summary>
    public AssemblyNodeId? ParentId { get; private set; }

    /// <summary>
    /// Business key, unique per business unit across all three levels.
    /// <para>
    /// Unique across levels rather than within one, because the code is what people
    /// quote to each other and what drawings carry: an <c>S1</c> section and an
    /// <c>S1</c> sub-assembly in the same plant is an ambiguity no downstream
    /// document can resolve.
    /// </para>
    /// </summary>
    public string Code { get; private set; } = null!;

    /// <summary>Legacy <c>AssemblyName</c>.</summary>
    public string Name { get; private set; } = null!;

    /// <summary>The code a person assigned, as opposed to <see cref="Code"/>.</summary>
    public string? ManualCode { get; private set; }

    public string? MachineType { get; private set; }

    /// <summary>What powers the node â€” motor, hydraulic, manual. Legacy <c>DrivenBy</c>.</summary>
    public string? DrivenBy { get; private set; }

    public string? DrawingPath { get; private set; }

    public string? TechnicalSpecification { get; private set; }

    public string? Remark { get; private set; }

    /// <summary>How many of this node its parent carries.</summary>
    public decimal? Quantity { get; private set; }

    /// <summary>Kilograms. Legacy <c>TotalWeight</c>.</summary>
    public decimal? WeightKg { get; private set; }

    /// <summary>Legacy <c>SrNo</c> â€” the order the node appears in on drawings and reports.</summary>
    public int? DisplaySequence { get; private set; }

    /// <summary>
    /// Whether the node may be used on new documents.
    /// <para>
    /// The only lifecycle flag these three masters carry. The legacy table also had
    /// an <c>IsApproved</c> latch, but the approval it recorded was raised and
    /// cleared by a mapping table this module does not own; reproducing the column
    /// without the workflow behind it would be a field nothing could ever change.
    /// It arrives with the Approvals module.
    /// </para>
    /// </summary>
    public bool IsActive { get; private set; } = true;

    public int BusinessUnitId { get; set; }

    public DateTimeOffset CreatedAtUtc { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTimeOffset? ModifiedAtUtc { get; set; }

    public Guid? ModifiedByUserId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTimeOffset? DeletedAtUtc { get; set; }

    public Guid? DeletedByUserId { get; set; }

    public byte[] RowVersion { get; set; } = [];

    /// <summary>
    /// Creates a node at the given level.
    /// </summary>
    /// <param name="level">Fixed for the lifetime of the record â€” see <see cref="Level"/>.</param>
    /// <param name="parentId">
    /// The node above. Whether it is required, and what level it must be, comes
    /// from <see cref="AssemblyLevels"/>; that the id actually resolves to a node at
    /// that level is checked by the handler, which is the only layer that can see
    /// other rows.
    /// </param>
    /// <param name="code">
    /// The business key, entered by the user.
    /// <para>
    /// This is the seam the future numbering scheme plugs into. The legacy
    /// generator â€” <c>"S" + (max(parsed tail) + 1)</c>, evaluated in memory over
    /// every row â€” is not reproduced: it duplicates codes under concurrency, it
    /// cannot express a per-machine or per-year series, and it was copy-pasted into
    /// four save methods that had already drifted apart. When
    /// <c>INumberSeriesAllocator</c> lands, the allocation happens in the handler
    /// and this parameter stops being supplied by the client. Nothing else about
    /// this class has to change.
    /// </para>
    /// </param>
    public static Result<AssemblyNode> Create(
        AssemblyLevel level,
        AssemblyNodeId? parentId,
        string code,
        string name,
        AssemblyNodeAttributes? attributes = null)
    {
        if (AssemblyLevels.RequiresParent(level) && parentId is null)
        {
            return Result.Failure<AssemblyNode>(AssemblyErrors.ParentRequired(level));
        }

        if (!AssemblyLevels.RequiresParent(level) && parentId is not null)
        {
            return Result.Failure<AssemblyNode>(AssemblyErrors.ParentNotAllowed(level));
        }

        var node = new AssemblyNode(
            AssemblyNodeId.New(),
            level,
            parentId,
            NormalizeCode(code),
            name.Trim());

        node.Apply(attributes ?? new AssemblyNodeAttributes());

        return Result.Success(node);
    }

    /// <summary>
    /// Applies an edit. The code and the level are not parameters â€” see
    /// <c>UpdateAssemblyNodeRequest</c> for why neither is editable.
    /// </summary>
    /// <param name="parentId">
    /// May differ from the current parent: moving an assembly to another section is
    /// an ordinary engineering change. The handler still checks the new parent's
    /// level and that the move does not create a cycle.
    /// </param>
    public Result Update(
        AssemblyNodeId? parentId,
        string name,
        bool isActive,
        AssemblyNodeAttributes? attributes = null)
    {
        if (AssemblyLevels.RequiresParent(Level) && parentId is null)
        {
            return Result.Failure(AssemblyErrors.ParentRequired(Level));
        }

        if (!AssemblyLevels.RequiresParent(Level) && parentId is not null)
        {
            return Result.Failure(AssemblyErrors.ParentNotAllowed(Level));
        }

        ParentId = parentId;
        Name = name.Trim();
        IsActive = isActive;

        Apply(attributes ?? new AssemblyNodeAttributes());

        return Result.Success();
    }

    /// <summary>
    /// Copies the descriptive fields in, normalising as it goes. Codes are
    /// upper-cased; free text is only trimmed, because upper-casing a technical
    /// specification destroys the case of the unit symbols in it.
    /// </summary>
    private void Apply(AssemblyNodeAttributes attributes)
    {
        ManualCode = CleanCode(attributes.ManualCode);
        MachineType = Clean(attributes.MachineType);
        DrivenBy = Clean(attributes.DrivenBy);
        DrawingPath = Clean(attributes.DrawingPath);
        TechnicalSpecification = Clean(attributes.TechnicalSpecification);
        Remark = Clean(attributes.Remark);
        Quantity = attributes.Quantity;
        WeightKg = attributes.WeightKg;
        DisplaySequence = attributes.DisplaySequence;
    }

    /// <summary>
    /// Upper-cases and trims, so <c>"s1"</c>, <c>"S1 "</c> and <c>"S1"</c> cannot
    /// become three different sections.
    /// </summary>
    private static string NormalizeCode(string value) => value.Trim().ToUpperInvariant();

    private static string? Clean(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static string? CleanCode(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : NormalizeCode(value);
}
