<Project Sdk="Microsoft.NET.Sdk">

  <!-- The only shared project allowed to see ASP.NET Core types. -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Erp.SharedKernel\Erp.SharedKernel.csproj" />
    <ProjectReference Include="..\Erp.BuildingBlocks.Application\Erp.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Erp.Contracts\Erp.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
