<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Erp.SharedKernel\Erp.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Erp.Contracts\Erp.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
  </ItemGroup>

</Project>
