import type { TreeColumn } from '@/components/tree-list/tree-list';
import type { MasterStatus } from '@/lib/api/types';

const STATUS_STYLES: Record<MasterStatus, string> = {
  Draft: 'bg-surface-3 text-ink-2',
  PendingApproval: 'bg-amber-500/15 text-amber-700 dark:text-amber-300',
  Approved: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300',
  Inactive: 'bg-rose-500/15 text-rose-700 dark:text-rose-300',
};

const STATUS_LABELS: Record<MasterStatus, string> = {
  Draft: 'Draft',
  PendingApproval: 'Pending approval',
  Approved: 'Approved',
  Inactive: 'Inactive',
};

/**
 * Column builders shared by every masters grid.
 *
 * These exist so a status pill is the same width, the same colour and the same
 * wording on all five screens without each one restating it — the legacy system
 * rendered status four different ways because each grid built its own.
 *
 * `T` is deliberately unconstrained. The row types are hand-written interfaces
 * today and generated by orval tomorrow, and an interface never satisfies
 * `Record<string, unknown>` — so requiring it would mean adding an index
 * signature to every DTO and losing the typo-checking those DTOs exist for.
 * Field access goes through {@link read} instead.
 */

/** Reads a field by name off a row whose shape the builder does not know. */
function read(row: unknown, field: string): unknown {
  return (row as Record<string, unknown>)[field];
}

/** A plain text column. `calculateCellValue` is what search, the filter row and CSV export read. */
export function textColumn<T>(
  dataField: string,
  caption: string,
  width: number,
  options: { mono?: boolean; align?: TreeColumn<T>['align']; defaultVisible?: boolean } = {},
): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 80,
    mono: options.mono,
    align: options.align,
    defaultVisible: options.defaultVisible,
    calculateCellValue: (row) => asText(read(row, dataField)),
  };
}

/**
 * A date column, rendered in the viewer's locale. The server never formats dates.
 *
 * `valueField` exists because the sort name and the JSON property do not always
 * agree: parts sort on `createdAt` but carry `createdAtUtc`. `dataField` has to
 * stay the server's name or sorting 400s, so the value is read separately.
 */
export function dateColumn<T>(
  dataField: string,
  caption: string,
  width = 130,
  valueField: string = dataField,
): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 100,
    calculateCellValue: (row) => {
      const value = read(row, valueField);
      return typeof value === 'string' && value ? new Date(value).toLocaleDateString('en-IN') : '—';
    },
  };
}

/** Whether the record is in use — separate from whether it is approved. */
export function activeColumn<T>(dataField = 'isActive'): TreeColumn<T> {
  const label = (row: T) => (read(row, dataField) ? 'Active' : 'Inactive');

  return {
    dataField,
    caption: 'Active',
    width: 92,
    minWidth: 80,
    align: 'center',
    calculateCellValue: label,
    cellRender: (row) => (
      <Pill tone={read(row, dataField) ? 'ok' : 'muted'}>{label(row)}</Pill>
    ),
  };
}

/** The approval lifecycle pill. */
export function statusColumn<T>(dataField = 'status'): TreeColumn<T> {
  return {
    dataField,
    caption: 'Status',
    width: 150,
    minWidth: 120,
    calculateCellValue: (row) => STATUS_LABELS[read(row, dataField) as MasterStatus] ?? '',
    cellRender: (row) => {
      const status = read(row, dataField) as MasterStatus;
      return (
        <span
          className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${STATUS_STYLES[status] ?? ''}`}
        >
          {STATUS_LABELS[status] ?? String(status)}
        </span>
      );
    },
  };
}

/** A yes/no column for plain booleans that carry no lifecycle meaning. */
export function booleanColumn<T>(dataField: string, caption: string, width = 150): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 90,
    align: 'center',
    calculateCellValue: (row) => (read(row, dataField) ? 'Yes' : 'No'),
  };
}

/**
 * As {@link booleanColumn}, but for a boolean that may be null.
 *
 * The distinction is not pedantry: "not applicable for service" and "nobody has
 * said yet" are different facts, and rendering both as "No" is how a field that
 * was never filled in becomes an answer somebody acts on.
 */
export function optionalBooleanColumn<T>(
  dataField: string,
  caption: string,
  width = 150,
  options: { defaultVisible?: boolean } = {},
): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 90,
    align: 'center',
    defaultVisible: options.defaultVisible,
    calculateCellValue: (row) => {
      const value = read(row, dataField);
      return value === null || value === undefined ? '—' : value ? 'Yes' : 'No';
    },
  };
}

/**
 * The row's position in the overall result, not its position on screen.
 *
 * The legacy grids all opened with a "Sr No" column, and people quote it to each
 * other. It is computed rather than stored: `__srNo` is stamped onto each row by
 * `MasterTreeList` from the page number and page size, so row 1 of page 3 reads 51
 * rather than 1. A stored ordinal would be a column that has to be renumbered
 * every time anything is inserted or removed.
 *
 * Not sortable and not filterable, because the server has no such field — offering
 * the control would produce a 400. Not hideable either: it is the anchor people
 * scan down, and a grid this wide is worse without it.
 */
export function serialNumberColumn<T>(): TreeColumn<T> {
  return {
    dataField: '__srNo',
    caption: 'Sr No',
    width: 72,
    minWidth: 56,
    align: 'right',
    allowSorting: false,
    allowFiltering: false,
    allowHiding: false,
    calculateCellValue: (row) => asText(read(row, '__srNo')),
  };
}

/**
 * A number, formatted in the viewer's locale and right-aligned so the digits line
 * up down the column. The server sends the raw number and never a formatted string.
 */
export function numberColumn<T>(
  dataField: string,
  caption: string,
  width = 120,
  options: { decimals?: number; defaultVisible?: boolean } = {},
): TreeColumn<T> {
  const { decimals = 0 } = options;

  return {
    dataField,
    caption,
    width,
    minWidth: 80,
    align: 'right',
    defaultVisible: options.defaultVisible,
    calculateCellValue: (row) => {
      const value = read(row, dataField);
      if (typeof value !== 'number' || Number.isNaN(value)) return '—';

      return value.toLocaleString('en-IN', {
        minimumFractionDigits: decimals,
        maximumFractionDigits: decimals,
      });
    },
    // Sorts on the number itself. Sorting the formatted text would order 1,000
    // before 9 because the comma sorts before the digit.
    calculateSortValue: (row) => {
      const value = read(row, dataField);
      return typeof value === 'number' ? value : Number.NEGATIVE_INFINITY;
    },
  };
}

/**
 * A column whose stored value is a code and whose meaning is a label — the legacy
 * grids' `lookup` with a fixed `dataSource`, such as gender `01`/`02`.
 *
 * An unmapped code renders as itself rather than as blank, so migrated data with a
 * value nobody anticipated is visible instead of silently disappearing.
 */
export function lookupColumn<T>(
  dataField: string,
  caption: string,
  labels: Record<string, string>,
  width = 120,
  options: { defaultVisible?: boolean } = {},
): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 80,
    align: 'center',
    defaultVisible: options.defaultVisible,
    calculateCellValue: (row) => {
      const value = read(row, dataField);
      if (value === null || value === undefined || value === '') return '—';

      const key = String(value);
      return labels[key] ?? key;
    },
  };
}

/** A list of short values — skills, strengths — joined for display and for export. */
export function tagsColumn<T>(
  dataField: string,
  caption: string,
  width = 200,
  options: { defaultVisible?: boolean } = {},
): TreeColumn<T> {
  return {
    dataField,
    caption,
    width,
    minWidth: 100,
    defaultVisible: options.defaultVisible,
    allowSorting: false,
    calculateCellValue: (row) => {
      const value = read(row, dataField);
      return Array.isArray(value) ? value.join(', ') : '';
    },
  };
}

function Pill({ tone, children }: { tone: 'ok' | 'muted'; children: React.ReactNode }) {
  return (
    <span
      className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
        tone === 'ok'
          ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300'
          : 'bg-surface-3 text-ink-3'
      }`}
    >
      {children}
    </span>
  );
}

function asText(value: unknown): string {
  if (value === null || value === undefined) return '';
  return String(value);
}
